server:
  port: 5051

spring:
  profiles:
    active: ${current.profile}
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 6600Fold
#    url: jdbc:mysql://localhost:3306/cheapsltrips?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
#    baseurl: http://localhost:5051
  application:
    name: cheap-sl-trips
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update